### ISSUE TITLE
0802 - UI PPT 작성 (~08/05)

### ISSUE THREAD

**Issue by loveAlakazam** [KHAcademyProject2020/Semi-Project#4]
**1. Use Case Diagram**
 정규동(@JungKyuDong ) , 정창섭(@werty12123 )

**2. 스토리보드**
유정하 (@JungHa-Yu ), 하민재(@Haminjae )

**3. Sequence Diagram**
김용연 (@kimyongyoen)

**Comment by ghost** [comment]
@kimyongyoen '공지사항 페이지에서 등록 버튼을 눌렀을 때 뜨는 창'을 스토리 보드에 추가해주시길 바랍니다.
